version: '3.9'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: .env

  web:
    build: .
    depends_on:
      - db
    command: >
      sh -c "make migrate &&
             make start"
    volumes:
      - static_data:/app/staticfiles
    expose:
      - 8000
    env_file: .env

  nginx:
    image: nginx:1.25.3-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static_data
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:
  static_data: