# Generated by Django 5.0.1 on 2024-01-24 11:10

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, 'Карта'), (1, 'Платежный счет')], verbose_name='Тип платежа')),
                ('card_type', models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT'), (2, 'PREPAID'), (3, 'SAVINGS'), (4, 'PLATINUM'), (5, 'TRAVEL'), (6, 'LOYALTY')], verbose_name='Тип карты')),
                ('account_type', models.PositiveSmallIntegerField(choices=[(0, 'Текущий (чековый)'), (1, 'Сберегательный'), (4, 'Бизнес'), (5, 'Зарплатный'), (6, 'Студенческий'), (7, 'Совместный'), (8, 'С высокой процентной ставкой')], verbose_name='Тип счёта')),
                ('owner_name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ожидает оплаты'), (1, 'Оплачена'), (2, 'Отменена')], verbose_name='Статус')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_requests.checkingaccount', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
            },
        ),
    ]
