# Generated by Django 5.0.1 on 2024-01-25 14:55

import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Текущий (чековый)'), (1, 'Сберегательный'), (4, 'Бизнес'), (5, 'Зарплатный'), (6, 'Студенческий'), (7, 'Совместный'), (8, 'С высокой процентной ставкой')], db_index=True, default=0, verbose_name='Тип счёта'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='card_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT'), (2, 'PREPAID'), (3, 'SAVINGS'), (4, 'PLATINUM'), (5, 'TRAVEL'), (6, 'LOYALTY')], db_index=True, default=0, verbose_name='Тип карты'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='limit',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('1000'), max_digits=10, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Карта'), (1, 'Платежный счет')], db_index=True, default=0, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ожидает оплаты'), (1, 'Оплачена'), (2, 'Отменена')], default=0, verbose_name='Статус'),
        ),
    ]
